### ISSUE TITLE
compute-applicable-methods not exported.

### ISSUE THREAD

**Issue by ghost** [mcna/closer-mop#1]
The generic function 'compute-applicable-methods' (unlike '-using-classes') is not exported but this is part of the MOP spec. Was this intentional ?

**Comment by brpocock** [comment]
This is an “in-house” fork of the project from http://sourceforge.net/projects/closer/ … you might have better results checking with upstream.
However (as a general Lisper, with no special knowledge of Closer-MOP), that function is in the CL package … http://clhs.lisp.se/Body/f_comput.htm … I would not expect Closer-MOP to re-export it, itself, unless it were filling in for a missing implementation.

**Comment by ghost** [comment]
Shoot; didn't see that. Sorry for the trouble.

**Comment by brpocock** [comment]
no worries :-)
